depth = 0;

n = 0;
image_speed = 0.35;
alarm[1] = 60;
global.seconds = 59;
global.minutes = 1;
angle = 0;
frame = 0;
global.pizza = 0;
global.pizzameter = 0;
global.pillarhunger = 4000;
uTime = shader_get_uniform(shdr_wind, "Time");
basement = 0;
shake_mag = 0;
shake_mag_acc = 0;
timestop = 1;
zoom = 0;
alpha = 1;