font = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0);
draw_set_font(font);
draw_set_halign(fa_center);
draw_set_color(c_white);
draw_text_transformed(448, 32, @"THANKS FOR PLAYING DEMO 2!!

GAME AND ANIMATIONS 
BY PIZZA TOWER GUY

LEVEL DESIGN BY
DARKONIUS MAVAKAR

MUSIC AND SOUNDS BY 
MR SAUCEMAN  FROSTIX  
DIM WIDDY POST ELVIS

THANKS TO ALL THE 
TESTERS ON THE DISCORD SERVER!!

PRESS START AND 
SELECT EXIT TO GO BACK TO THE TITLE SCREEN 
AND TRY THE OTHER LEVELS!!", 0.5, 0.5, 1);