instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
instance_create(x + 32, y + 32, obj_debris);
tile_layer_delete_at(1, x, y);
tile_layer_delete_at(1, x + 32, y);
tile_layer_delete_at(1, x + 32, y + 32);
tile_layer_delete_at(1, x, y + 32);
scr_sound(choose(sound_destroyblock1, sound_destroyblock2));